const API = {
    AUTH_LOGIN: `/auth/login`,
    AUTH_REGISTER: `/auth/register`,
    AUTH_GETME: `/auth/getMe`,

    PRODUCT_GETALL: `/product/getAll`,
    PRODUCT_GETBY: (id: string) => `/product/getBy/${id}`,
    PRODUCT_CREATE: `/product/create`,
    PRODUCT_UPDATE: (id: string) => `/product/update/${id}`,
    PRODUCT_DELETE: (id: string) => `/product/delete/${id}`,
    PRODUCT_CHANGESTATUS: (id: string) => `/product/changeStatus/${id}`,
    PRODUCT_CREATE_MANY: `/product/create/many`,

    CATEGORY_GETALL: `/category/getAll`,
    CATEGORY_GETBY: (id: string) => `/category/getBy/${id}`,
    CATEGORY_CREATE: `/category/create`,
    CATEGORY_UPDATE: (id: string) => `/category/update/${id}`,
    CATEGORY_DELETE: (id: string) => `/category/delete/${id}`,
    CATEGORY_CHANGESTATUS: (id: string) => `/category/changeStatus/${id}`,
    CATEGORY_CREATE_MANY: `/category/create/many`,

    COLOR_GETALL: `/color/getAll`,
    COLOR_GETBY: (id: string) => `/color/getBy/${id}`,
    COLOR_CREATE: `/color/create`,
    COLOR_UPDATE: (id: string) => `/color/update/${id}`,
    COLOR_DELETE: (id: string) => `/color/delete/${id}`,
    COLOR_CHANGESTATUS: (id: string) => `/color/changeStatus/${id}`,
    COLOR_CREATE_MANY: `/color/create/many`,

    SIZE_GETALL: `/size/getAll`,
    SIZE_GETBY: (id: string) => `/size/getBy/${id}`,
    SIZE_CREATE: `/size/create`,
    SIZE_UPDATE: (id: string) => `/size/update/${id}`,
    SIZE_DELETE: (id: string) => `/size/delete/${id}`,
    SIZE_CHANGESTATUS: (id: string) => `/size/changeStatus/${id}`,
    SIZE_CREATE_MANY: `/size/create/many`,

    MATERIAL_GETALL: `/material/getAll`,
    MATERIAL_GETBY: (id: string) => `/material/getBy/${id}`,
    MATERIAL_CREATE: `/material/create`,
    MATERIAL_UPDATE: (id: string) => `/material/update/${id}`,
    MATERIAL_DELETE: (id: string) => `/material/delete/${id}`,
    MATERIAL_CHANGESTATUS: (id: string) => `/material/changeStatus/${id}`,
    MATERIAL_CREATE_MANY: `/material/create/many`,

    SIDEBAR_GETALL: `/sidebar/getAll`,
    SIDEBAR_GETBY: (id: string) => `/sidebar/getBy/${id}`,
    SIDEBAR_CREATE: `/sidebar/create`,
    SIDEBAR_UPDATE: (id: string) => `/sidebar/update/${id}`,
    SIDEBAR_DELETE: (id: string) => `/sidebar/delete/${id}`,
    SIDEBAR_CHANGESTATUS: (id: string) => `/sidebar/changeStatus/${id}`,
    SIDEBAR_CREATE_MANY: `/sidebar/create/many`,

    ICON_GETALL: `/icon/getAll`,
    ICON_GETBY: (id: string) => `/icon/getBy/${id}`,
    ICON_CREATE: `/icon/create`,
    ICON_UPDATE: (id: string) => `/icon/update/${id}`,
    ICON_DELETE: (id: string) => `/icon/delete/${id}`,
    ICON_CHANGESTATUS: (id: string) => `/icon/changeStatus/${id}`,
    ICON_CREATE_MANY: `/icon/create/many`,

    USER_GETALL: `/user/getAll`,
    USER_GETBY: (id: string) => `/user/getBy/${id}`,
    USER_CREATE: `/user/create`,
    USER_UPDATE: (id: string) => `/user/update/${id}`,
    USER_DELETE: (id: string) => `/user/delete/${id}`,
    USER_CHANGESTATUS: (id: string) => `/user/changeStatus/${id}`,
    USER_CREATE_MANY: `/user/create/many`,

    ROLE_GETALL: `/role/getAll`,
    ROLE_GETBY: (id: string) => `/role/getBy/${id}`,
    ROLE_CREATE: `/role/create`,
    ROLE_UPDATE: (id: string) => `/role/update/${id}`,
    ROLE_DELETE: (id: string) => `/role/delete/${id}`,
    ROLE_CHANGESTATUS: (id: string) => `/role/changeStatus/${id}`,
    ROLE_CREATE_MANY: `/role/create/many`,

    USER_ROLE_GETALL: `/user-role/getAll`,
    USER_ROLE_GETBY: (id: string) => `/user-role/getBy/${id}`,
    USER_ROLE_CREATE: `/user-role/create`,
    USER_ROLE_UPDATE: (id: string) => `/user-role/update/${id}`,
    USER_ROLE_DELETE: (id: string) => `/user-role/delete/${id}`,
    USER_ROLE_CHANGESTATUS: (id: string) => `/user-role/changeStatus/${id}`,
    USER_ROLE_CREATE_MANY: `/user-role/create/many`,
    USER_ROLE_DELETE_MANY: `/user-role/delete/hardmany`,

    PAYMENTMETHOD_GETALL: `/payment-method/getAll`,
    PAYMENTMETHOD_GETBY: (id: string) => `/payment-method/getBy/${id}`,
    PAYMENTMETHOD_CREATE: `/payment-method/create`,
    PAYMENTMETHOD_UPDATE: (id: string) => `/payment-method/update/${id}`,
    PAYMENTMETHOD_DELETE: (id: string) => `/payment-method/delete/${id}`,
    PAYMENTMETHOD_CHANGESTATUS: (id: string) => `/payment-method/changeStatus/${id}`,
    PAYMENTMETHOD_CREATE_MANY: `/payment-method/create/many`,

    ORDERMETHOD_GETALL: `/order-method/getAll`,
    ORDERMETHOD_GETBY: (id: string) => `/order-method/getBy/${id}`,
    ORDERMETHOD_CREATE: `/order-method/create`,
    ORDERMETHOD_UPDATE: (id: string) => `/order-method/update/${id}`,
    ORDERMETHOD_DELETE: (id: string) => `/order-method/delete/${id}`,
    ORDERMETHOD_CHANGESTATUS: (id: string) => `/order-method/changeStatus/${id}`,
    ORDERMETHOD_CREATE_MANY: `/order-method/create/many`,

    VOUCHER_GETALL: `/voucher/getAll`,
    VOUCHER_GETBY: (id: string) => `/voucher/getBy/${id}`,
    VOUCHER_CREATE: `/voucher/create`,
    VOUCHER_UPDATE: (id: string) => `/voucher/update/${id}`,
    VOUCHER_DELETE: (id: string) => `/voucher/delete/${id}`,
    VOUCHER_CHANGESTATUS: (id: string) => `/voucher/changeStatus/${id}`,
    VOUCHER_CREATE_MANY: `/voucher/create/many`,

    ORDER_GETALL: `/order/getAll`,
    ORDER_GETBY: (id: string) => `/order/getBy/${id}`,
    ORDER_CREATE: `/order/create`,
    ORDER_UPDATE: (id: string) => `/order/update/${id}`,
    ORDER_DELETE: (id: string) => `/order/delete/${id}`,
    ORDER_CHANGESTATUS: (id: string) => `/order/changeStatus/${id}`,
    ORDER_CREATE_MANY: `/order/create/many`,

    CUSTOMER_GETALL: `/customer/getAll`,
    CUSTOMER_GETBY: (id: string) => `/customer/getBy/${id}`,
    CUSTOMER_CREATE: `/customer/create`,
    CUSTOMER_UPDATE: (id: string) => `/customer/update/${id}`,
    CUSTOMER_DELETE: (id: string) => `/customer/delete/${id}`,
    CUSTOMER_CHANGESTATUS: (id: string) => `/customer/changeStatus/${id}`,
    CUSTOMER_CREATE_MANY: `/customer/create/many`,

    CUSTOMERTYPE_GETALL: `/customer-type/getAll`,
    CUSTOMERTYPE_GETBY: (id: string) => `/customer-type/getBy/${id}`,
    CUSTOMERTYPE_CREATE: `/customer-type/create`,
    CUSTOMERTYPE_UPDATE: (id: string) => `/customer-type/update/${id}`,
    CUSTOMERTYPE_DELETE: (id: string) => `/customer-type/delete/${id}`,
    CUSTOMERTYPE_CHANGESTATUS: (id: string) => `/customer-type/changeStatus/${id}`,
    CUSTOMERTYPE_CREATE_MANY: `/customer-type/create/many`,

    EMPLOYEE_GETALL: `/employee/getAll`,
    EMPLOYEE_GETBY: (id: string) => `/employee/getBy/${id}`,
    EMPLOYEE_CREATE: `/employee/create`,
    EMPLOYEE_UPDATE: (id: string) => `/employee/update/${id}`,
    EMPLOYEE_DELETE: (id: string) => `/employee/delete/${id}`,
    EMPLOYEE_CHANGESTATUS: (id: string) => `/employee/changeStatus/${id}`,
    EMPLOYEE_CREATE_MANY: `/employee/create/many`,

    CART_GETALL: `/cart/getAll`,
    CART_GETBY: (id: string) => `/cart/getBy/${id}`,
    CART_CREATE: `/cart/create`,
    CART_UPDATE: (id: string) => `/cart/update/${id}`,
    CART_DELETE: (id: string) => `/cart/delete/${id}`,
    CART_CHANGESTATUS: (id: string) => `/cart/changeStatus/${id}`,
    CART_CREATE_MANY: `/cart/create/many`,
}

export default API;